# .readthedocs.yaml
# Read the Docs configuration file.

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.10"

# 1. Insall deps
python:
  install:
    - method: uv
      command: sync
      groups:
        - docs

# 2. Build the docs.
build:
  html:
  - uv run properdocs build -f docs/properdocs.yml --site-dir $READTHEDOCS_OUTPUT/html
