# .readthedocs.yaml
# Read the Docs configuration file.

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.10"
  jobs:
    # 1. Install uv into the environment setup 
    post_create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest    
  commands:
  # Install deps and then build docs.
    - uv sync --group docs
    - properdocs build -f docs/properdocs.yml --site-dir $READTHEDOCS_OUTPUT/html
