# Image definition for MLTE backend container.

FROM mlte-python

# Create the default storage location.
RUN mkdir /mnt/store

# Install MLTE.
WORKDIR /mnt/app/
RUN uv sync

# Set the MLTE backend server as the entry point.
ENTRYPOINT ["uv", "run", "mlte", "backend"]
