# Image for creating a distributable package of MLTE.

FROM mlte-python

# Copy the static web site back into the MLTE folder structure.
COPY --from=mlte-frontend-build /mnt/app/mlte/frontend/nuxt-app/.output /mnt/app/mlte/frontend/nuxt-app/.output

# Install dev deps and build sdist and wheel.
RUN uv sync --no-install-project --group tools
RUN uv build

# Check if the description/readme in the created packages are ok for PyPi.
RUN uv run twine check dist/*
