# Image definition for MLTE backend container.
FROM mlte-python

WORKDIR /mnt/app

# Install dev dependencies
RUN uv sync --no-install-project --group dev --group demo --all-extras --no-cache

# Install jq for demo QA
RUN apt-get install -y jq

# Install git for docs QA
RUN apt-get update && apt-get install -y git

# Copy in files needed for QA/CI
COPY .git .git
COPY Makefile .

# Install MLTE package
RUN uv sync --group dev --group demo --all-extras --no-cache

ENTRYPOINT ["make"]
