# Dockerfile
#
# Image definition for MLTE container, built from a PyPi package.

FROM python:3.12.10-slim-bookworm

# Base deps for compiling wheels.
RUN apt-get update && apt-get install -y build-essential

# Setup MLTE and dependencies.
RUN pip install mlte[rdbs,frontend,gpu]

# Get the command from an arg.
ARG MLTE_COMMAND
ENV MLTE_COMMAND=${MLTE_COMMAND}

ENTRYPOINT ["mlte", "${MLTE_COMMAND}"]
